services:
  db:
    image: postgres
    container_name: psql-database
    env_file: .env
    hostname: localhost
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER:      ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_DB:        psql-database
    volumes: [postgres-data:/var/lib/postgresql/data]
    restart: always
    profiles: [db, bot]
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: .env
    depends_on: [db]
    ports: ["5050:80"]
    environment:
      PGADMIN_DEFAULT_EMAIL:    ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: always
    profiles: [db, bot]
  bot:
    build: .
    container_name: my-bot
    env_file: .env
    restart: always
    profiles: [bot, only-bot]
  
volumes:
  postgres-data: